import { prisma } from '../lib/prisma';

async function main() {
    console.log('Cleaning mock data generated by the seeder...');

    // 1. Delete all DailyMetric where totalRevenue is exactly 12450.00 (the seed amount)
    // or netProfit is 7900.00
    const deletedMetrics = await prisma.dailyMetric.deleteMany({
        where: {
            OR: [
                { totalRevenue: 12450.00 },
                { netProfit: 7900.00 }
            ]
        }
    });
    console.log(`Deleted ${deletedMetrics.count} mock DailyMetric entries.`);

    // 2. Delete all Orders where customerName starts with "Client "
    const deletedOrders = await prisma.order.deleteMany({
        where: {
            customerName: {
                startsWith: 'Client '
            }
        }
    });

    console.log(`Deleted ${deletedOrders.count} mock Order entries.`);
    console.log('Database is now clean from sample metrics and orders.');
}

main()
    .catch(e => console.error(e))
    .finally(() => prisma.$disconnect());
